apiVersion: v2
name: server
description: Kubelens Server - Multi-Cluster Kubernetes Dashboard Backend
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - kubernetes
  - server
  - api
home: https://github.com/kubelensai/kubelens
sources:
  - https://github.com/kubelensai/kubelens
maintainers:
  - name: Son Nguyen
    email: son@example.com

dependencies:
  - name: postgresql
    version: "18.1.3"
    repository: https://charts.bitnami.com/bitnami
    condition: database.postgresql.deploy
    alias: postgresql
  - name: mysql
    version: "11.1.18"
    repository: https://charts.bitnami.com/bitnami
    condition: database.mysql.deploy
    alias: mysql
