apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "server.fullname" . }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if and .Values.initContainer.enabled (ne .Values.database.type "sqlite") }}
      initContainers:
      {{- if eq .Values.database.type "postgresql" }}
      - name: wait-for-postgres
        image: "{{ .Values.initContainer.image.repository }}:{{ .Values.initContainer.image.tag }}"
        imagePullPolicy: {{ .Values.initContainer.image.pullPolicy }}
        {{- if .Values.database.postgresql.deploy }}
        command: ['sh', '-c', 'until nc -zv {{ .Release.Name }}-postgresql 5432; do echo "Waiting for PostgreSQL..."; sleep 2; done']
        {{- else }}
        command: ['sh', '-c', 'until nc -zv {{ .Values.database.postgresql.external.host }} {{ .Values.database.postgresql.external.port }}; do echo "Waiting for PostgreSQL..."; sleep 2; done']
        {{- end }}
        resources:
          {{- toYaml .Values.initContainer.resources | nindent 10 }}
      {{- else if eq .Values.database.type "mysql" }}
      - name: wait-for-mysql
        image: "{{ .Values.initContainer.image.repository }}:{{ .Values.initContainer.image.tag }}"
        imagePullPolicy: {{ .Values.initContainer.image.pullPolicy }}
        {{- if .Values.database.mysql.deploy }}
        command: ['sh', '-c', 'until nc -zv {{ .Release.Name }}-mysql 3306; do echo "Waiting for MySQL..."; sleep 2; done']
        {{- else }}
        command: ['sh', '-c', 'until nc -zv {{ .Values.database.mysql.external.host }} {{ .Values.database.mysql.external.port }}; do echo "Waiting for MySQL..."; sleep 2; done']
        {{- end }}
        resources:
          {{- toYaml .Values.initContainer.resources | nindent 10 }}
      {{- end }}
      {{- end }}
      containers:
      - name: server
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        env:
          {{- toYaml .Values.env | nindent 10 }}
          {{- if .Values.adminPassword }}
          - name: KUBELENS_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "server.fullname" . }}-admin
                key: admin-password
          {{- end }}
          {{- if .Values.rateLimit }}
          - name: KUBELENS_GLOBAL_RATE_LIMIT_PER_MIN
            value: {{ .Values.rateLimit.global | quote }}
          - name: KUBELENS_LOGIN_RATE_LIMIT_PER_MIN
            value: {{ .Values.rateLimit.login | quote }}
          {{- end }}
          {{- if eq .Values.database.type "sqlite" }}
          - name: KUBELENS_DATABASE_TYPE
            value: "sqlite"
          {{- if .Values.database.sqlite.deploy }}
          - name: KUBELENS_DATABASE_PATH
            value: {{ .Values.database.sqlite.builtin.path }}
          {{- else }}
          {{- /* External SQLite */}}
          - name: KUBELENS_DATABASE_PATH
            value: {{ .Values.database.sqlite.external.path }}
          {{- end }}
          {{- else if eq .Values.database.type "postgresql" }}
          - name: KUBELENS_DATABASE_TYPE
            value: "postgres"
          {{- if .Values.database.postgresql.deploy }}
          - name: KUBELENS_DATABASE_HOST
            value: "{{ .Release.Name }}-postgresql"
          - name: KUBELENS_DATABASE_PORT
            value: "5432"
          - name: KUBELENS_DATABASE_NAME
            value: {{ .Values.postgresql.auth.database | quote }}
          - name: KUBELENS_DATABASE_USER
            value: {{ .Values.postgresql.auth.username | quote }}
          - name: KUBELENS_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-postgresql
                key: password
          - name: KUBELENS_DATABASE_SSLMODE
            value: "disable"
          {{- else }}
          {{- /* External PostgreSQL */}}
          - name: KUBELENS_DATABASE_HOST
            value: {{ .Values.database.postgresql.external.host | quote }}
          - name: KUBELENS_DATABASE_PORT
            value: {{ .Values.database.postgresql.external.port | quote }}
          - name: KUBELENS_DATABASE_NAME
            value: {{ .Values.database.postgresql.external.database | quote }}
          - name: KUBELENS_DATABASE_USER
            value: {{ .Values.database.postgresql.external.user | quote }}
          - name: KUBELENS_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "server.fullname" . }}-database
                key: password
          - name: KUBELENS_DATABASE_SSLMODE
            value: {{ .Values.database.postgresql.external.sslmode | quote }}
          {{- end }}
          {{- else if eq .Values.database.type "mysql" }}
          - name: KUBELENS_DATABASE_TYPE
            value: "mysql"
          {{- if .Values.database.mysql.deploy }}
          - name: KUBELENS_DATABASE_HOST
            value: "{{ .Release.Name }}-mysql"
          - name: KUBELENS_DATABASE_PORT
            value: "3306"
          - name: KUBELENS_DATABASE_NAME
            value: {{ .Values.mysql.auth.database | quote }}
          - name: KUBELENS_DATABASE_USER
            value: {{ .Values.mysql.auth.username | quote }}
          - name: KUBELENS_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-mysql
                key: mysql-password
          {{- else }}
          {{- /* External MySQL */}}
          - name: KUBELENS_DATABASE_HOST
            value: {{ .Values.database.mysql.external.host | quote }}
          - name: KUBELENS_DATABASE_PORT
            value: {{ .Values.database.mysql.external.port | quote }}
          - name: KUBELENS_DATABASE_NAME
            value: {{ .Values.database.mysql.external.database | quote }}
          - name: KUBELENS_DATABASE_USER
            value: {{ .Values.database.mysql.external.user | quote }}
          - name: KUBELENS_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "server.fullname" . }}-database
                key: password
          {{- end }}
          {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        {{- if and (eq .Values.database.type "sqlite") .Values.database.sqlite.deploy .Values.database.sqlite.builtin.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "server.fullname" . }}-data
        {{- else }}
        emptyDir: {}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

