{{- if and (eq .Values.database.type "sqlite") .Values.database.sqlite.deploy .Values.database.sqlite.builtin.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "server.fullname" . }}-data
  labels:
    {{- include "server.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.database.sqlite.builtin.persistence.accessMode }}
  {{- if .Values.database.sqlite.builtin.persistence.storageClass }}
  {{- if (eq "-" .Values.database.sqlite.builtin.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.database.sqlite.builtin.persistence.storageClass }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.database.sqlite.builtin.persistence.size }}
{{- end }}

