{{- if .Values.adminPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "server.fullname" . }}-admin
  labels:
    {{- include "server.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ .Values.adminPassword | b64enc | quote }}
{{- end }}

