apiVersion: v2
name: app
description: Kubelens App - Multi-Cluster Kubernetes Dashboard UI
type: application
version: 1.0.0-alpha.1
appVersion: "1.0.0-alpha.1"
keywords:
  - kubernetes
  - app
  - dashboard
  - ui
home: https://github.com/sonnguyen/kubelens
sources:
  - https://github.com/sonnguyen/kubelens
maintainers:
  - name: Son Nguyen
    email: son@example.com

